### ISSUE TITLE
Decompose reqs into backlogs and sprints

### ISSUE THREAD

**Issue by SnowJP** [trystkelly/uv-sim#4]
What I have so far

Backlogs

1.	Draw Use Case Diagram
2.	Write comparison of Scrum and Other process model
3.	Draw UML diagram of prototype
4.	Program input section
5.	Program individual instructions
6.	Program output and display functions
7.	Write test cases
8.	Record meeting log
9.	Write code comments explaining functions

Sprints

**Comment by trystkelly** [comment]
1. Two independent prototypes, make comparison (2, 4, 5, 6)
2. Refactor for classes, conceptualize (1, 3, 7, 8, 9)
