### ISSUE TITLE
Pros and cons of scrum and another model

### ISSUE THREAD

**Issue by SnowJP** [trystkelly/uv-sim#5]
what I have so far

Scrum vs. XP (Milestone 1 Deliverable 3)

We compared the Scrum process model with XP because we focused more on XP than on other processes in class, and so had a better understanding of it. The main difference between the two seems to be that XP is a more formalized system than Scrum. We have listed some of the pros and cons of each process below.

Scrum Pro #1 - At this stage of the project, we don't know how important one feature is versus another. Scrum treats them equally, which works well in this case.

Scrum Pro #2 - Since Scrum doesn't prescribe programming practices, it is easier to understand all the components.

Scrum Con #1 - Scrum encourages longer sprints, which we don't have time for with this project.

XP pro #1 - XP allows changes during an interation, whereas in Scrum, you should wait until the current sprint is finished. Since the turnaround for our project is short and we are learning about the requirements as we go, that aspect of XP would be convenient.

XP con #1 - Our group is small and we work remotely, so the pair programming XP uses won't work well.  In XP one person programs and another back seat drives, with the intention of catching all the needed features. It is a nice safety feature, but unrealistic for this project.

**Comment by trystkelly** [comment]
What I did a bit ago:
-----

Waterfall Model vs Agile Scrum

Waterfall Model advantages
•	Systematic and ordered
•	Each team can focus on their own area all at once
•	Phases of development integrated into model
•	Easy start/middle/finish of each block
Waterfall Model disadvantages
•	Not very flexible, moving forward only
•	Limited interaction between teams
•	“Thumb-twiddling” while a phase doesn’t involve a particular team

Agile Scrum advantages
•	Communication between teams
•	Analysis after each completed block
•	Entire group can collaborate and discuss to move forward
•	Flexibility in development order
•	Fast feedback and adaptation to requirements
